import java.net.Inet4Address

data class Config(
    val gitRepo:String,
    val sshSecretKeyPath:String,
    val ipAddress: String="auto" ,//autoで自動判別
    val tcpPorts:Array<Int>,
    val udpPorts:Array<Int>
) {
    //Auto Generated by いんてりじぇー
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Config

        if (gitRepo != other.gitRepo) return false
        if (sshSecretKeyPath != other.sshSecretKeyPath) return false
        if (ipAddress != other.ipAddress) return false
        if (!tcpPorts.contentEquals(other.tcpPorts)) return false
        if (!udpPorts.contentEquals(other.udpPorts)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = gitRepo.hashCode()
        result = 31 * result + sshSecretKeyPath.hashCode()
        result = 31 * result + ipAddress.hashCode()
        result = 31 * result + tcpPorts.contentHashCode()
        result = 31 * result + udpPorts.contentHashCode()
        return result
    }
}
